-- Get all columns from fact tables only
SELECT 
    t.TABLE_NAME,
    c.COLUMN_NAME,
    c.DATA_TYPE,
    c.IS_NULLABLE,
    c.ORDINAL_POSITION,
    CASE 
        WHEN c.COLUMN_NAME LIKE '%Key' THEN 'FK_TO_DIM'
        WHEN c.COLUMN_NAME LIKE '%ID' THEN 'FK_OR_ID'
        WHEN c.COLUMN_NAME = 'LoanId' THEN 'BUSINESS_KEY'
        ELSE 'MEASURE'
    END AS ColumnPurpose
FROM INFORMATION_SCHEMA.TABLES t
INNER JOIN INFORMATION_SCHEMA.COLUMNS c 
    ON t.TABLE_NAME = c.TABLE_NAME 
    AND t.TABLE_SCHEMA = c.TABLE_SCHEMA
WHERE t.TABLE_SCHEMA = 'fact'
ORDER BY t.TABLE_NAME, c.ORDINAL_POSITION;
